class Plante:
    def __init__(self, nom, saison, localisation):
        self.nom = nom
        self.saison = saison
        self.localisation = localisation

        p1 = Plante("Alkanet", "printemps", "forêt")
        p2 = Plante("Arlan", "été", "forêt")
        p3 = Plante("Ashine", "été", "forêt")
        p4 = Plante("Barr", "été", "forêt")
        p5 = Plante("Belramba", "printemps", "forêt")
        p6 = Plante("Calcéna", "été", "forêt")
        p7 = Plante("Dramallon", "automne", "forêt")
        p8 = Plante("Entriste", "été", "forêt")
        p9 = Plante("Falsifal", "printemps", "forêt")
        p10 = Plante("Ferfendu", "été", "forêt")
        p11 = Plante("Fétrefe", "automne", "forêt")
        p12 = Plante("Gardax", "automne", "forêt")
        p13 = Plante("Golcorone", "été", "forêt")
        p14 = Plante("Hélival", "été", "forêt")
        p15 = Plante("Lunort", "été", "forêt")
        p16 = Plante("Milorte", "été", "forêt")
        p17 = Plante("Palmath", "été", "forêt")
        p18 = Plante("Sherpur", "été", "forêt")
        p19 = Plante("Vilerge", "été", "forêt")
        p20 = Plante("Xosorrel", "automne", "forêt")
        p21 = Plante("Alleha", "été", "plaine")
        p22 = Plante("Amarans", "été", "plaine")
        p23 = Plante("Asarabacca", "été", "plaine")
        p24 = Plante("Bisette", "été", "plaine")
        p25 = Plante("Borage", "été", "plaine")
        p26 = Plante("Callin", "été", "plaine")
        p27 = Plante("Cinq Feuilles", "été", "plaine")
        p28 = Plante("Dorose", "été", "plaine")
        p29 = Plante("Fenouilly", "été", "plaine")
        p30 = Plante("Flousse", "été", "plaine")
        p31 = Plante("Foulaine", "été", "plaine")
        p32 = Plante("Garigne", "automne", "plaine")
        p33 = Plante("Haquedi", "été", "plaine")
        p34 = Plante("Jaffray", "été", "plaine")
        p35 = Plante("Laumpor", "été", "plaine")
        p36 = Plante("Lessentor", "automne", "plaine")
        p37 = Plante("Maserote", "été", "plaine")
        p37 = Plante("Mélande", "été", "plaine")
        p38 = Plante("Navouh", "été", "plaine")
        p39 = Plante("Olvar", "été", "plaine")
        p40 = Plante("Saraceco", "été", "plaine")
        p41 = Plante("Tanariske", "été", "plaine")
        p42 = Plante("Trovas", "printemps", "plaine")
        p43 = Plante("Ur", "été", "plaine")
        p44 = Plante("Wodero", "été", "plaine")
        p45 = Plante("Arpusar", "été", "montagne")
        p46 = Plante("Birnot", "été", "montagne")
        p46 = Plante("Cofrêle","été", "montagne")
        p47 = Plante("Culkas", "printemps", "montagne")
        p48 = Plante("Degiik", "automne", "montagne")
        p49 = Plante("Eldas", "automne", "montagne")
        p50 = Plante("Gabruche" "automne", "montagne")
        p51 = Plante("Harir", "été", "montagne")
        p52 = Plante("Ironar", "printemps", "montagne")
        p53 = Plante("Kelventari", "été", "montagne")
        p54 = Plante("Mandragore", "printemps", "montagne")
        p55 = Plante("Marmalleau", "été", "montagne")
        p55 = Plante("Mogarli", "automne", "montagne")
        p56 = Plante("Pattran", "automne", "montagne")
        p57 = Plante("Qurl", "été", "montagne")
        p58 = Plante("Bastit", "été", "marais")
        p59 = Plante("Blarot", "printemps", "marais")
        p60 = Plante("Damatère", "été", "marais")
        p61 = Plante("Darsurion", "été", "marais")
        p62 = Plante("Déchale", "automne", "marais")
        p63 = Plante("Ebure", "printemps", "marais")
        p64 = Plante("Jojopopo", "printemps", "marais")
        p65 = Plante("Oède", "été", "marais")
        p66 = Plante("Parlas", "été", "marais")
        p67 = Plante("Salnica", "automne", "marais")
        p68 = Plante("Anserke", " printemps", "désert")
        p69 = Plante("Bélan", "printemps", "désert")
        p70 = Plante("Blabert", "automne", "désert")
        p71 = Plante("Kilmatur", "printemps", "désert")
        p72 = Plante("Percechaussées", "automne", "désert")
        p73 = Plante("Tamors", "printemps", "désert")
        p74 = Plante("Bursthelas", "été", "littoral")
        p75 = Plante("Calamus", "été", "littoral")
        p76 = Plante("Chasseloup", "printemps", "littoral")
        p77 = Plante("Colerte", "été", "littoral")
        p78 = Plante("Covette", "automne", "littoral")
        p79 = Plante("Ditanie", "été", "littoral")
        p80 = Plante("Draffe", "été", "littoral")
        p81 = Plante("Gylvire", "été", "littoral")
        p82 = Plante("Macabaté", "printemps", "littoral")
        p83 = Plante("Toréape", "été", "littoral")
        p84 = Plante("Archangélique", "automne", "arctique")
        p85 = Plante("Arkasu", "automne", "arctique")
        p86 = Plante("Attanar", " printemps", "arctique")
        p87 = Plante("Coparnie", "printemps", "arctique")
        p88 = Plante("Delrean", "printemps", "arctique")
        p89 = Plante("Yaretalion", "automne", "arctique")



print("Bonjour et bienvenue sur D&D Plant Picker !")

saison = input("En quelle saison sommes-nous ? (printemps, été, automne ou hiver)")
print(saison)
localisation = input("Où vous situez-vous ? (forêt, plaine, montagne, marais, désert ou arctique ?)")
print(localisation)
